### Registro do usuário
POST https://backbookshelf.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name": "Clara",
    "email": "clara@gmail.com",
    "password": "1234"
}

### Autenticação do usuário
POST https://backbookshelf.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "email": "clara@gmail.com",
    "password": "1234"
}